version: '{branch}-{build}'
environment:
  PY_PYTHON: 3.7-32
install:
- cmd: >-
    set PATH=C:\Python37\Scripts;%PATH%

    python -m pip install -U pip

    python -m pip install wheel

    py -m pip install scons

    py -m pip install markdown
before_build:
- ps: $env:IS_DEV = ($env:APPVEYOR_REPO_TAG -eq "false") -or ($env:APPVEYOR_REPO_TAG_NAME -match "dev")
build_script:
- cmd: scons dev=%IS_DEV%

test_script:
# Unit Tests (Python)
 - ps: |
     $errorCode=0
     py ./tests/unit/__init__.py
     if($LastExitCode -ne 0) {
      $errorCode=$LastExitCode
      Add-AppveyorMessage "Unit test failure"
     }
     else
     {
      Add-AppveyorMessage "Unit test success"
     }
     if($errorCode -ne 0) { $host.SetShouldExit($errorCode) }

artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
  
before_deploy:
- ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Release $(APPVEYOR_REPO_TAG_NAME)
  description: This is the release $(APPVEYOR_REPO_TAG_NAME) of the $(REPO_NAME) addon for the NVDA screen reader built and uploaded to GitHub using Appveyor.

  auth_token:
    secure: J2hRjB9oCLWUZqYR+JgbqGMD/PKtnUAl01rx5OTwoV1mF69s2ETSMyxUiy2ZT9TZ
  artifact: addon
  on:
    appveyor_repo_tag: true